FROM ubuntu
# FROM amd64=ubuntu:16.04 arm64=aarch64/ubuntu:16.04 arm=armhf/ubuntu:16.04

RUN apt-get update && apt-get install -y build-essential pkg-config wget bison flex iptables-dev libnftnl-dev libmnl-dev gperf libglib2.0-dev libkmod-dev  zlib1g-dev liblzma-dev uuid-dev libblkid-dev libestr-dev libjson-c-dev autoconf automake libtool libssl-dev nasm perl acl-dev libpopt-dev liblvm2-dev
COPY bin/strato /sbin/
