#!/bin/bash
set -e

BASE=packages
ORG=stratopkg

if [ -n "$1" ]; then
    BASE=$1
fi

source $(dirname $0)/version
cd $(dirname $0)/..

mkdir -p dist

./bin/strato index ${BASE} dist

for i in $BASE/*; do
    name=$(basename ${i})
    tag="${name}:${TAG}"

    echo Building ${tag} from ${i}
    if [ -e ${i}/prebuild.sh ]; then
        ${i}/prebuild.sh
    fi

    if dapper -d --build -f ${i}/Dockerfile -- -t package ${i}; then
        ./bin/strato extract ${i} ./dist
    elif [ "$?" != "42" ]; then
        exit 1
    else
        echo "Skipping ${tag}"
    fi
done
