#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

CONST="-X github.com/joshwget/strato/src/version.Version=${VERSION}"

go build -ldflags="${CONST} -s -w" -o bin/strato src/main.go
GOOS=linux GOARCH=amd64 go build -ldflags="${CONST} -s -w" -o bin/strato_amd64 src/main.go
GOOS=linux GOARCH=arm go build -ldflags="${CONST} -s -w" -o bin/strato_arm src/main.go
GOOS=linux GOARCH=arm64 go build -ldflags="${CONST} -s -w" -o bin/strato_arm64 src/main.go
