#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

CONST="-X github.com/joshwget/strato/version.Version=${VERSION}"

go build -ldflags="${CONST} -s -w" -o bin/strato
GOOS=linux GOARCH=amd64 go build -ldflags="${CONST} -s -w" -o bin/strato_amd64
GOOS=linux GOARCH=arm go build -ldflags="${CONST} -s -w" -o bin/strato_arm
GOOS=linux GOARCH=arm64 go build -ldflags="${CONST} -s -w" -o bin/strato_arm64

cd extract
go build -o ../bin/extract
cd -
