#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

BUILD=build
ASSETS=assets

mkdir -p ${BUILD}

install -m 0755 -d \
  ${BUILD}/etc \
  ${BUILD}/etc/ssl \
  ${BUILD}/home \
  ${BUILD}/run \
  ${BUILD}/usr \
  ${BUILD}/usr/bin \
  ${BUILD}/usr/sbin \
  ${BUILD}/usr/share \
  ${BUILD}/var/cache \
  ${BUILD}/var/cache/misc \
  ${BUILD}/var/lib \
  ${BUILD}/var/lib/misc \
  ${BUILD}/var/local \
  ${BUILD}/var/log \
  ${BUILD}/var/run

install -m 0555 -d ${BUILD}/var/empty
install -m 0700 -d ${BUILD}/root
install -m 1755 -d ${BUILD}/tmp ${BUILD}/var/tmp

cp -r ${ASSETS}/certs ${BUILD}/etc/ssl
cp ${ASSETS}/group ${ASSETS}/passwd ${ASSETS}/profile ${ASSETS}/shadow ${BUILD}/etc

#./strato add --dir=${BUILD} layout

tar -xf ${ASSETS}/${ARCH}/gccbase.tar -C ${BUILD}
tar -xf ${ASSETS}/${ARCH}/libgcc.tar -C ${BUILD}
tar -xf ${ASSETS}/${ARCH}/libc6.tar -C ${BUILD}
rm -rf ${BUILD}/usr/share/*

./strato add --dir=${BUILD} busybox

cd ${BUILD}
tar -cvf rootfs.tar .
cd -
mv ${BUILD}/rootfs.tar .
rm -rf ${BUILD}

docker build -t strato -f Dockerfile .
docker tag strato strato:${TAG}
docker build -t strato-min -f Dockerfile.min .
docker tag strato-min strato-min:${TAG}

rm rootfs.tar
