#!/bin/bash
set -e

BASE=packages

if [ -n "$1" ]; then
    BASE=$1
fi

source $(dirname $0)/version
cd $(dirname $0)/..

dapper -d --build -f Dockerfile.build -- -t strato-build .

./bin/strato index ${BASE} dist
./bin/strato build-all ${BASE} dist
