#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

LDFLAGS="-X github.com/rancher/strato/src/version.Version=${VERSION} -s -w"
ARCHES=(amd64 arm arm64)

go build -ldflags="${LDFLAGS}" -o bin/strato src/main.go
for ARCH in ${ARCHES[@]}; do
    GOOS=linux GOARCH=${ARCH} go build -ldflags="${LDFLAGS}" -o bin/strato_${ARCH} src/main.go
done
