#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

BUILD=build

mkdir -p ${BUILD}
./bin/strato --source=${PWD}/dist/ add --dir=${BUILD} base-layout ca-certificates glibc busybox

cd ${BUILD}
tar -cvf rootfs.tar .
cd -
mv ${BUILD}/rootfs.tar .
rm -rf ${BUILD}

docker build -t strato -f Dockerfile .
docker tag strato strato:${TAG}

rm rootfs.tar
