#!/bin/bash

set -e

cd $(dirname $0)/..

if docker inspect --format "{{.State.Status}}"  strato-server ; then
	# we don't know if this was started in a different dir..
	docker rm -f strato-server
fi

mkdir -p dist

# for rancher os test builds
cp bin/strato* dist/

docker run -d --name strato-server -v $(pwd)/dist:/var/www/html:ro joshix/caddy
IP=$(docker inspect --format "{{.NetworkSettings.Networks.bridge.IPAddress}}" strato-server)
echo "http://$IP:2015/" > assets/repositories-build

echo "Connect using $(cat assets/repositories-build)"
